// <auto-generated />
using System;
using GymAkhada.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymAkhada.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260703073105_AddAppUsers")]
    partial class AddAppUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymAkhada.Models.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("GymMember_ID")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("GymMember_ID");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("GymAkhada.Models.GymCategory", b =>
                {
                    b.Property<int>("Gym_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Gym_ID"));

                    b.Property<string>("Gym_Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gym_categoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Gym_ID");

                    b.ToTable("GymCategories");
                });

            modelBuilder.Entity("GymAkhada.Models.GymMember", b =>
                {
                    b.Property<int>("GymMember_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GymMember_ID"));

                    b.Property<string>("AadharNumber")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("Age")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Gym_ID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("WeightKg")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("GymMember_ID");

                    b.HasIndex("Gym_ID");

                    b.ToTable("GymMembers");
                });

            modelBuilder.Entity("GymAkhada.Models.GymSubcategory", b =>
                {
                    b.Property<int>("GymSub_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GymSub_ID"));

                    b.Property<int>("GymSub_age")
                        .HasColumnType("int");

                    b.Property<decimal>("GymWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Gym_ID")
                        .HasColumnType("int");

                    b.HasKey("GymSub_ID");

                    b.HasIndex("Gym_ID");

                    b.ToTable("GymSubcategories");
                });

            modelBuilder.Entity("GymAkhada.Models.AppUser", b =>
                {
                    b.HasOne("GymAkhada.Models.GymMember", "GymMember")
                        .WithMany()
                        .HasForeignKey("GymMember_ID");

                    b.Navigation("GymMember");
                });

            modelBuilder.Entity("GymAkhada.Models.GymMember", b =>
                {
                    b.HasOne("GymAkhada.Models.GymCategory", "GymCategory")
                        .WithMany()
                        .HasForeignKey("Gym_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GymCategory");
                });

            modelBuilder.Entity("GymAkhada.Models.GymSubcategory", b =>
                {
                    b.HasOne("GymAkhada.Models.GymCategory", "GymCategory")
                        .WithMany("Subcategories")
                        .HasForeignKey("Gym_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GymCategory");
                });

            modelBuilder.Entity("GymAkhada.Models.GymCategory", b =>
                {
                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
